parameters:
    w3c_lifecycle_events.auto_dispatch: ''

services:
    W3C\LifecycleEventsBundle\Services\AttributeGetter:
    W3C\LifecycleEventsBundle\Services\LifecycleEventsDispatcher:
        arguments: [ '@event_dispatcher', '%w3c_lifecycle_events.auto_dispatch%' ]
    W3C\LifecycleEventsBundle\EventListener\LifecycleEventsListener:
        arguments: [ '@w3c_lifecycle_events.dispatcher', '@w3c_lifecycle_events.attribute_getter' ]
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: preRemove }
            - { name: doctrine.event_listener, event: preSoftDelete }
            - { name: doctrine.event_listener, event: preUpdate }
    W3C\LifecycleEventsBundle\EventListener\LifecyclePropertyEventsListener:
        arguments: [ '@w3c_lifecycle_events.dispatcher', '@w3c_lifecycle_events.attribute_getter' ]
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
    W3C\LifecycleEventsBundle\EventListener\PostFlushListener:
        arguments: [ '@w3c_lifecycle_events.dispatcher' ]
        tags:
            - { name: doctrine.event_listener, event: postFlush }

    w3c_lifecycle_events.attribute_getter:
        alias: W3C\LifecycleEventsBundle\Services\AttributeGetter
    w3c_lifecycle_events.dispatcher:
        alias: W3C\LifecycleEventsBundle\Services\LifecycleEventsDispatcher
    w3c_lifecycle_events.listener:
        alias: W3C\LifecycleEventsBundle\EventListener\LifecycleEventsListener
    w3c_lifecycle_events.property_listener:
        alias: W3C\LifecycleEventsBundle\EventListener\LifecyclePropertyEventsListener
    w3c_lifecycle_events.post_flush_listener:
        alias: W3C\LifecycleEventsBundle\EventListener\PostFlushListener
